=== daiqiaobing/mango-core/src/main/resource/mango-core.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://maven.apache.org/POM/4.0.0"
           xmlns="http://maven.apache.org/POM/4.0.0"  elementFormDefault="qualified">
    <xs:element name="configuration">
        <xs:complexType>
            <xs:all>
                <xs:element name="title" type="xs:string" default="应用配置文件" minOccurs="0"/>
                <xs:element name="property" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="key"/>
                            <xs:element name="value"/>
                            <xs:element name="type"/>
                            <xs:element name="description"  minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== daiqiaobing/mango-core/src/main/resource/core.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration  xmlns="https://github.com/daiqiaobing/mango-core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/daiqiaobing/mango-core https://github.com/daiqiaobing/mango-core/blob/dev/src/main/resource/mango-core.xsd"  >

    <title>配置文件</title>

    <property>
        <key>aoi</key>
        <value>test.property</value>
        <type>property</type>
        <scope>single</scope>
    </property>

    <property>
        <key>1</key>
        <value></value>
        <type>property</type>
        <scope>single</scope>
    </property>
</configuration>

=== daiqiaobing/mango-core/src/test/resource/core.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration  xmlns="https://github.com/daiqiaobing/mango-core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/daiqiaobing/mango-core https://github.com/daiqiaobing/mango-core/blob/dev/src/main/resource/mango-core.xsd"  >

    <title>配置文件</title>

    <property>
        <key>aoi</key>
        <value>test.properties</value>
        <type>property</type>
        <scope>global</scope>
    </property>

    <property>
        <key>aoi1</key>
        <value>test.yaml</value>
        <type>yaml</type>
        <scope>global</scope>
    </property>
</configuration>
